<?php


namespace App\Services\Telegram\Facades;


use App\Services\Telegram\Core\ViewController;
use Illuminate\Support\Facades\Facade;

class TeleView extends Facade
{
       protected static function getFacadeAccessor()
       {
           ViewController::class; // TODO: Change the autogenerated stub
       }
}
